export const phrases = [
  {
    id: 1,
    quote: "A felicidade de sua vida depende da qualidade de seus pensamentos.",
    author: "Marco Aurélio",
  },
  {
    id: 2,
    quote: "Não conte os dias, faça os dias contarem.",
    author: "Muhammad Ali",
  },
  {
    id: 3,
    quote: "Somos aquilo que repetidamente fazemos.",
    author: "Aristóteles",
  },
  {
    id: 4,
    quote: "A disciplina é a ponte entre metas e realizações.",
    author: "Jim Rohn",
  },
  { id: 5, quote: "Feito é melhor que perfeito.", author: "Sheryl Sandberg" },
  {
    id: 6,
    quote: "Comece onde você está, use o que tem.",
    author: "Arthur Ashe",
  },
  {
    id: 7,
    quote: "Ação é a chave fundamental para o sucesso.",
    author: "Pablo Picasso",
  },
  {
    id: 8,
    quote: "O sucesso é a soma de pequenos esforços diários.",
    author: "Robert Collier",
  },
  {
    id: 9,
    quote: "A melhor maneira de prever o futuro é criá-lo.",
    author: "Peter Drucker",
  },
  {
    id: 10,
    quote: "Primeiro criamos hábitos, depois eles nos criam.",
    author: "John Dryden",
  },
  { id: 11, quote: "Coragem é resistência ao medo.", author: "Mark Twain" },
  {
    id: 12,
    quote: "Grandes atos são feitos de pequenas ações.",
    author: "Lao Tsé",
  },
  {
    id: 13,
    quote: "A excelência não é um ato, mas um hábito.",
    author: "Aristóteles",
  },
  { id: 14, quote: "Seja a mudança que deseja ver.", author: "Mahatma Gandhi" },
  {
    id: 15,
    quote: "O que você faz diariamente importa.",
    author: "John C. Maxwell",
  },
  {
    id: 16,
    quote: "A persistência realiza o impossível.",
    author: "Thomas Edison",
  },
  {
    id: 17,
    quote: "Sonhos não funcionam sem ação.",
    author: "John C. Maxwell",
  },
  {
    id: 18,
    quote: "O esforço contínuo supera o talento.",
    author: "Will Smith",
  },
  {
    id: 19,
    quote: "A disciplina pesa gramas, o arrependimento pesa toneladas.",
    author: "Jim Rohn",
  },
  {
    id: 20,
    quote: "Pequenas melhorias constantes levam ao sucesso.",
    author: "James Clear",
  },
  {
    id: 21,
    quote: "A simplicidade é a sofisticação máxima.",
    author: "Leonardo da Vinci",
  },
  { id: 22, quote: "Faça o difícil enquanto é fácil.", author: "Lao Tsé" },
  {
    id: 23,
    quote: "A sorte favorece a mente preparada.",
    author: "Louis Pasteur",
  },
  { id: 24, quote: "O sucesso nasce do hábito.", author: "Aristóteles" },
  {
    id: 25,
    quote: "A única maneira de fazer um grande trabalho é amar o que faz.",
    author: "Steve Jobs",
  },
  {
    id: 26,
    quote: "Não espere por oportunidades, crie-as.",
    author: "George Bernard Shaw",
  },
  {
    id: 27,
    quote: "A jornada de mil milhas começa com um passo.",
    author: "Lao Tsé",
  },
  {
    id: 28,
    quote: "A dúvida mata mais sonhos que o fracasso.",
    author: "Suzy Kassem",
  },
  { id: 29, quote: "A coragem começa com aparecer.", author: "Brené Brown" },
  {
    id: 30,
    quote: "O sucesso depende da preparação prévia.",
    author: "Confúcio",
  },
  {
    id: 31,
    quote:
      "A mente que se abre a uma nova ideia jamais volta ao tamanho original.",
    author: "Albert Einstein",
  },
  {
    id: 32,
    quote: "Você perde 100% dos tiros que não dá.",
    author: "Wayne Gretzky",
  },
  { id: 33, quote: "A motivação inicia, o hábito mantém.", author: "Jim Ryun" },
  {
    id: 34,
    quote: "Grandes resultados exigem tempo.",
    author: "Warren Buffett",
  },
  { id: 35, quote: "A prática leva à perfeição.", author: "Vince Lombardi" },
  { id: 36, quote: "A disciplina supera o talento.", author: "Kobe Bryant" },
  {
    id: 37,
    quote: "O sucesso é ir de fracasso em fracasso sem perder o entusiasmo.",
    author: "Winston Churchill",
  },
  {
    id: 38,
    quote: "Não é sobre ser perfeito, é sobre ser melhor.",
    author: "Tony Robbins",
  },
  { id: 39, quote: "Faça hoje o que outros não fazem.", author: "Jerry Rice" },
  {
    id: 40,
    quote: "Se você quer algo novo, faça algo novo.",
    author: "Georg Christoph Lichtenberg",
  },
  {
    id: 41,
    quote: "Seja forte quando estiver fraco.",
    author: "Arnold Schwarzenegger",
  },
  { id: 42, quote: "O esforço compensa.", author: "Michael Jordan" },
  { id: 43, quote: "Treine duro, lute fácil.", author: "Bruce Lee" },
  { id: 44, quote: "Conhece-te a ti mesmo.", author: "Sócrates" },
  { id: 45, quote: "A constância vence.", author: "David Goggins" },
  { id: 46, quote: "Progresso, não perfeição.", author: "Winston Churchill" },
  { id: 47, quote: "A mente governa o corpo.", author: "Napoleon Hill" },
  {
    id: 48,
    quote: "Faça o melhor com o que tem.",
    author: "Theodore Roosevelt",
  },
  {
    id: 49,
    quote: "A preparação encontra a oportunidade.",
    author: "Oprah Winfrey",
  },
  {
    id: 50,
    quote: "Você é aquilo que faz repetidamente.",
    author: "Aristóteles",
  },
  {
    id: 51,
    quote: "Nunca é tarde para ser quem você poderia ter sido.",
    author: "George Eliot",
  },
  { id: 52, quote: "Grandes coisas levam tempo.", author: "Jeff Bezos" },
  { id: 53, quote: "Persistência é tudo.", author: "Calvin Coolidge" },
  { id: 54, quote: "O foco cria resultados.", author: "Jack Canfield" },
  { id: 55, quote: "Ação cria motivação.", author: "Mel Robbins" },
  { id: 56, quote: "Faça acontecer.", author: "Richard Branson" },
  { id: 57, quote: "Você pode mais do que imagina.", author: "Les Brown" },
  {
    id: 58,
    quote: "Comece antes de estar pronto.",
    author: "Steven Pressfield",
  },
  { id: 59, quote: "A coragem é um músculo.", author: "Brené Brown" },
  { id: 60, quote: "Mantenha-se faminto.", author: "Steve Jobs" },
  { id: 61, quote: "Aprenda sempre.", author: "Benjamin Franklin" },
  { id: 62, quote: "Tempo é o recurso mais valioso.", author: "Brian Tracy" },
  { id: 63, quote: "Construa hábitos fortes.", author: "James Clear" },
  { id: 64, quote: "Decida e execute.", author: "Tony Robbins" },
  { id: 65, quote: "Trabalhe duro em silêncio.", author: "Frank Ocean" },
  { id: 66, quote: "Nada substitui o trabalho duro.", author: "Thomas Edison" },
  { id: 67, quote: "Seja melhor a cada dia.", author: "John Wooden" },
  { id: 68, quote: "Grandes líderes servem.", author: "Simon Sinek" },
  { id: 69, quote: "Domine o básico.", author: "Bruce Lee" },
  { id: 70, quote: "Aprenda com erros.", author: "Bill Gates" },
  { id: 71, quote: "O começo é metade.", author: "Aristóteles" },
  { id: 72, quote: "A mente forte vence.", author: "Marcus Aurelius" },
  { id: 73, quote: "Disciplina diária transforma.", author: "Robin Sharma" },
  { id: 74, quote: "Seja constante.", author: "James Clear" },
  { id: 75, quote: "Faça o necessário.", author: "Elon Musk" },
  { id: 76, quote: "Crie seu caminho.", author: "Ralph Waldo Emerson" },
  { id: 77, quote: "A clareza vem da ação.", author: "Marie Forleo" },
  { id: 78, quote: "Seja resiliente.", author: "Angela Duckworth" },
  { id: 79, quote: "Persistir é vencer.", author: "Napoleon Hill" },
  { id: 80, quote: "Continue avançando.", author: "Nelson Mandela" },
  { id: 81, quote: "Seja responsável.", author: "Jocko Willink" },
  { id: 82, quote: "Menos falar, mais fazer.", author: "Henry Ford" },
  { id: 83, quote: "Faça melhor amanhã.", author: "Tim Cook" },
  { id: 84, quote: "Vença a si mesmo.", author: "Platão" },
  { id: 85, quote: "Trabalhe com propósito.", author: "Howard Schultz" },
  { id: 86, quote: "Construa seu legado.", author: "Kobe Bryant" },
  { id: 87, quote: "Continue treinando.", author: "Cristiano Ronaldo" },
  { id: 88, quote: "Nunca desista.", author: "Serena Williams" },
  { id: 89, quote: "Busque evolução.", author: "Novak Djokovic" },
  { id: 90, quote: "Foque no essencial.", author: "Greg McKeown" },
  { id: 91, quote: "Simplifique tudo.", author: "Leonardo da Vinci" },
  { id: 92, quote: "Pense grande.", author: "Donald Trump" },
  { id: 93, quote: "Seja disciplinado.", author: "Jocko Willink" },
  { id: 94, quote: "Construa consistência.", author: "James Clear" },
  { id: 95, quote: "Faça o que importa.", author: "Cal Newport" },
  { id: 96, quote: "Aprenda rápido.", author: "Reid Hoffman" },
  { id: 97, quote: "A prática diária importa.", author: "John Wooden" },
  { id: 98, quote: "Crie hábitos fortes.", author: "Charles Duhigg" },
  { id: 99, quote: "Progresso constante.", author: "Ray Dalio" },
  { id: 100, quote: "Seja adaptável.", author: "Charles Darwin" },
  { id: 101, quote: "A disciplina vence.", author: "David Goggins" },
  { id: 102, quote: "Busque excelência.", author: "Vince Lombardi" },
  { id: 103, quote: "Faça com paixão.", author: "Tony Hsieh" },
  { id: 104, quote: "Construa algo grande.", author: "Elon Musk" },
  { id: 105, quote: "Comece pequeno.", author: "Jeff Bezos" },
  { id: 106, quote: "Evolua sempre.", author: "Bruce Lee" },
  { id: 107, quote: "Domine sua mente.", author: "Marco Aurélio" },
  { id: 108, quote: "Tenha propósito.", author: "Simon Sinek" },
  { id: 109, quote: "Seja persistente.", author: "Thomas Edison" },
  { id: 110, quote: "Foque no processo.", author: "Nick Saban" },
  { id: 111, quote: "Repita o essencial.", author: "James Clear" },
  { id: 112, quote: "Construa hábitos diários.", author: "BJ Fogg" },
  { id: 113, quote: "Trabalhe com foco.", author: "Cal Newport" },
  { id: 114, quote: "Treine consistência.", author: "Robin Sharma" },
  { id: 115, quote: "Mantenha o ritmo.", author: "David Goggins" },
  { id: 116, quote: "Progresso diário.", author: "James Clear" },
  { id: 117, quote: "Faça acontecer hoje.", author: "Tony Robbins" },
  { id: 118, quote: "Construa seu futuro.", author: "Peter Drucker" },
  { id: 119, quote: "Ação cria confiança.", author: "Mel Robbins" },
  { id: 120, quote: "Continue aprendendo.", author: "Bill Gates" },
  { id: 121, quote: "Melhore sempre.", author: "John Wooden" },
  { id: 122, quote: "Busque disciplina.", author: "Jocko Willink" },
  { id: 123, quote: "Seja resiliente.", author: "Angela Duckworth" },
  { id: 124, quote: "Construa rotina.", author: "James Clear" },
  { id: 125, quote: "Treine foco.", author: "Cal Newport" },
  { id: 126, quote: "Continue evoluindo.", author: "Robin Sharma" },
  { id: 127, quote: "Hoje constrói amanhã.", author: "Peter Drucker" },
];
